from random import randint

vokabeln = {
"tabula, ae f.": "Tafel, Gemälde",
"tacere, taceo, tacui, tacitum": "schweigen, verschweigen",
"tangere, tango, tetigi, tactum": "berühren",
"attingere, attingo, attigi, attactum": "berühren",
"contingere, contingo, contigi, contactum": "berühren",
"contingit": "es gelingt, es glückt",
"integer (gra, grum)": "unberührt, unversehrt",
"in integrum restituere": "in den ursprünglichen Zustand bringen",
"tardus (a, um)": "langsam",
"tegere, tego, texi, tectum": "(be-)decken",
"tectum, i n.": "Dach",
"tellus, uris f.": "Erde",
"telum, i n.": "Geschoss, Waffe",

"templum, i n.": "Heiligtum",
"temptare od. tentare, tento, tentavi, tentatum": "betasten, versuchen",
"tempus, poris n.": "Zeit",
"temperare, tempero, temperavi, temperatum": "das rechte (Zeit-)Maß festsetzen, mäßigen",
"rem publicam temperare": "den Staat ordnen, - lenken",
"sibi temperare": "sich beherrschen",
"hosti temperare": "den Feind schonen",
"tempestas, atis f.": "1. Zeitabschnitt; 2. Unwetter",
"tendere, tendo, tetendi, tentum": "dehnen, spannen, strecken",
"contendere, contendo, contendi, contentum": "sich anstrengen, eilen, kämpfen",
"contendo hoc facere.": "Ich beeile mich, das zu tun.",
"contendo hoc verum esse.": "Ich behaupte, dass das wahr ist.",
"contentio, onis f.": "Anspannung, Streit",
"intendere, intendo, intendi, intentum": "anspannen, richten auf",
"animo (Abl.) intendere": "beabsichtigen",
"ostendere, ostendo, ostendi, ostentum": "entgegenstrecken, zeigen",
"tenuis, tenuis, tenue; is": "dünn, zart, schwach",
"tenere, teneo, tenui, tentum": "(fest-)halten",
"copias castris tenere": "die Truppen im Lager halten",
"abstinere, abstineo, abstinui, abstentum": "fern halten, sich enthalten",
"(ab) iniuria abstinere": "(sich) von einem Unrecht fern halten",
"continere, contineo, continui, contentum": "festhalten, umfassen",
"continuus (a, um)": "zusammenhÃ¤ngend, ununterbrochen",
"continuo (Adv.)": "sofort(?)",
"obtinere, obtineo, obtinui, obtentum": "festhalten, innehaben",
"pertinere, pertineo, pertinui": "sich erstrecken, sich beziehen",
"retinere, retineo, retinui, retentum": "festhalten",
"sustinere, sustineo, sustinui": "aushalten",
"tergum, i n.": "Rücken",
"terga vertere": "fliehen",
"terra, ae f.": "Erde, Land",
"terrere, terreo, terrui, territum": "(er-)schrecken (tr.)",
"perterrere, perterreo, perterrui, perterritum": "gewaltig erschrecken (tr.), einschüchtern",

"testis, is m./f.": "Zeuge; Zeugin",
"testimonium, ii n.": "Zeugnis, Beweis",
"timere, timeo, timui": "fürchten, sich scheuen",
"timor, oris m.": "Furcht",
"tollere, tollo, sustuli, sublatum": "hoch-, aufheben, beseitigen",
"tolerare, tolero, toleravi, toleratum": "ertragen",
"totus (a, um) (Gen. totius; Dat. toti)": "ganz",
"trahere, traho, traxi, tractum": "ziehen, schleppen",
"tractare, tracto, tractavi, tractatum": "handhaben, behandeln, unterhandeln",
"tres, tres, tria; trium": "drei",
"tertius (a, um)": "der dritte",
"triginta (undekl.)": "dreißig",
"tribuere, tribuo, tribui, tributum": "zuteilen",
"honori tribuere": "zur Ehre anrechnen",
"tribunus, i m.": "Bezirksleiter, Tribun",
"tristis, tristis, triste; is": "traurig",
"tueri": "(betrachten), beschützen",
"tutus (a, um); Adv. tuto": "geschützt, sicher",
"tumultus, us m.": "Lärm, Aufruhr",
"turba, ae f.": "1. Getümmel, Lärm; 2. (Menschen- )Menge",
"perturbare, perturbo, pertubavi, pertubatum": "verwirren",
"turpis, turpis, turpe; is": "hässlich",
"turris, is f.": "Turm, Burg",
"ulterior, ulterior, ulterius; oris": "jenseitig, weiter",
"ultimus (a, um) (Superl.)": "Äußerster, letzter",
"unda, ae f.": "Welle, Flut",
"unus (a, um) (Gen. Unius; Dat. Uni)": "einer, ein",
"urbs, urbis f.": "Stadt",
"urgere, urgeo, ursi": "(be-)drängen",
"uti, uitor, usus sum": "gebrauchen",
"auctoritate uti": "Ansehen genießen",
"utillis, utillis, utille; is": "nützlich",
"usus, us m.": "Gebrauch, Nutzen, Übung",
"uxor, oris f.": "Gattin"
}

latein = list(vokabeln.keys())
deutsch = list(vokabeln.values())
